# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build And Push
  displayName: Build and push an image
  jobs:
  - job: BuildPush
    displayName: Build and push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push an image
      inputs:
        command: buildAndPush
        buildContext: .
        repository: lecturedocker/mindbridge-frontend
        dockerfile: '.docker/frontend.Dockerfile'
        containerRegistry: 'Docker Hub'
        tags: |
          $(tag)
