jwt:
    secret: 9i3Bk8SJ3CfqIm+v9JJjHc5PGmqNmevaXDLYX4k0sW9hmhuvA6rTNWIM6uISlbVWcn28bMs+gY+P3LLzRytHMQ==

    #30 min
    secs_to_expire_access: 1800

    #30 days
    secs_to_expire_refresh: 2592000

oauth2:
    redirect-uris: http://localhost:3000

spring:
    security:
        oauth2:
            client:
                registration:
                    google:
<<<<<<< HEAD
                        client-id: 531677136441-2ihh1vter6jrb0fdla7qkf9mjq87tfqm.apps.googleusercontent.com
                        client-secret: ejtZmFhG9eiwL2lJ3EIhVbxA
=======
                        client-id: {GOOGLE_CLIENT_ID}
                        client-secret: {GOOGLE_CLIENT_SECRET}
>>>>>>> ff40577a61e4fb36ca184a81fc852805286a3c44
                        redirectUri: "{baseUrl}/auth/oauth2/code/{registrationId}"
                        scope:
                            - email
                            - profile
                    github:
<<<<<<< HEAD
                        clientId: a0edbdbedc83304611be
                        clientSecret: cdd0d0ac844becf45c2f04d2b0e91fa23686af93
=======
                        clientId: {GITHUB_CLIENT_ID}
                        clientSecret: {GITHUB_CLIENT_SECRET}
>>>>>>> ff40577a61e4fb36ca184a81fc852805286a3c44
                        redirectUri: "{baseUrl}/auth/oauth2/code/{registrationId}"
                        scope:
                            - email
                            - public_profile
                    facebook:
<<<<<<< HEAD
                        clientId: 554266855704800
                        clientSecret: 9c678ada2f6ab4c17c3c3be63082eaea
=======
                        clientId: {FACEBOOK_CLIENT_ID}
                        clientSecret: {FACEBOOK_CLIENT_SECRET}
>>>>>>> ff40577a61e4fb36ca184a81fc852805286a3c44
                        redirectUri: "{baseUrl}/auth/oauth2/code/{registrationId}"
                        scope:
                            - email
                            - public_profile
