version: '3'

services:
  backend:
    image: lecturedocker/backend:latest
    container_name: backend
    ports:
      - '5000:5000'
    env_file:
      - ../.env/backend.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  frontend:
    image: lecturedocker/frontend:latest
    container_name: frontend
    domainname: 'mindbridge'
    depends_on:
      - backend
    ports:
      - '80:80'
      - '443:443'    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - /data/certs:/etc/nginx/certs
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      - /etc/letsencrypt/live/mindbridge.westeurope.cloudapp.azure.com/cert.pem:/etc/letsencrypt/live/knewless.tk/cert.pem
      - /etc/letsencrypt/live/mindbridge.westeurope.cloudapp.azure.com/chain.pem:/etc/letsencrypt/live/mindbridge.westeurope.cloudapp.azure.com/chain.pem
      - /etc/letsencrypt/live/mindbridge.westeurope.cloudapp.azure.com/fullchain.pem:/etc/letsencrypt/live/mindbridge.westeurope.cloudapp.azure.com/fullchain.pem
      - /etc/letsencrypt/live/mindbridge.westeurope.cloudapp.azure.com/privkey.pem:/etc/letsencrypt/live/mindbridge.westeurope.cloudapp.azure.com/privkey.pem   

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    env_file:
      - ../.env/elastic.env
    # volumes:
    #   - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  shared:
    driver: local