name: Deploy Mindbridge Staging

on:  
  pull_request:
    branches: 
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build and Push Backend docker image
        id: docker-build-backend        
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/backend.Dockerfile
          push: true
          tags: ${{ secrets.BACKEND_DOCKER_REGISTRY }}:staging

    - name: Build and Push Frontend docker image
      id: docker-build-frontend        
      uses: docker/build-push-action@v2
      with:
        context: .
        file: .docker/frontend.Dockerfile
        push: true
        tags: ${{ secrets.FRONTEND_DOCKER_REGISTRY }}:staging    

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: .aws/main-task-definition.json
        service: mindbridge-service
        cluster: mindbridge-cluster
        wait-for-service-stability: true

    - name: Update Pull Request
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            ### Mindbridge Staging Deploy ⚙️

            #### Check the staging portal: 1.1.1.1 

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
