name: 'Terraform'

on:  
  push:
    branches:
      - main
      - dev

jobs:
  terraform:
    name: 'Project Deploy'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build And Push Frontend docker image
        id: docker-build-frontend  
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/frontend.Dockerfile
          push: true
          tags: ${{ secrets.FRONTEND_DOCKER_REGISTRY }}:latest

      - name: Login to azure with docker        
        uses: azure/docker-login@v1
        with:
          login-server: index.docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create ACI context
        working-directory: .docker
        run: |
          docker context create aci myacicontext --resource-group=${{ secrets.RESOURCE_GROUP }}
          docker context use myacicontext
          docker-compose up -d

      # - name: 'Deploy frontend to Azure Container Instances'
      #   id: deploy-frontend
      #   uses: 'azure/aci-deploy@v1'
      #   with:
      #     resource-group: ${{ secrets.RESOURCE_GROUP }}
      #     dns-name-label: mindbridge
      #     image: ${{ secrets.FRONTEND_DOCKER_REGISTRY }}:latest
      #     registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      #     registry-username: ${{ secrets.DOCKER_USER }}
      #     registry-password: ${{ secrets.DOCKER_PASSWORD }}
      #     name: frontend
      #     location: 'west us'